### ISSUE TITLE
Can't build 'tricore' project

### ISSUE THREAD

**Issue by syntroniks** [mumbel/ghidra#16]
**Describe the bug**
When running `gradle --init-script gradle/support/fetchDependencies.gradle init`, the process fails because `\gradleScripts\processorUtils.gradle` does not exist

**Output**
> * Where:
> Build file 'C:\Users\user\Desktop\ghidra\ghidra\Ghidra\Processors\tricore\build.gradle' line: 7
> 
> * What went wrong:
> A problem occurred evaluating project ':tricore'.
> > Could not read script 'C:\Users\user\Desktop\ghidra\ghidra\gradleScripts\processorUtils.gradle' as it does not exist.

**Environment (please complete the following information):**
 - OS: Windows 10 18932
 - Java Version: openjdk 11.0.3 2019-04-16
 - OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.3+7)
 - OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.3+7, mixed mode)
 - Ghidra Version: forked from this repo, branch `tricore` 7fc76dbca414199

**Comment by syntroniks** [comment]
I think this is a 9.0.x vs 9.1.x thing -- the folders look like they moved around and gradleScripts is now Gradle. I'm not sure where the contents of processorUtils went.

**Comment by mumbel** [comment]
Thanks for catching that.  I did a fetch upstream and forgot to update the gradle file, should be good now
