### ISSUE TITLE
Use separate git repositories for processor specs

### ISSUE THREAD

**Issue by VTCAKAVSMoACE** [mumbel/ghidra#18]
**Is your feature request related to a problem? Please describe.**
I would like to use your RISCV processor implementation, but have my own forks as well.

**Describe the solution you'd like**
Using a separate git repo with a submodule in this one would be much preferred to a dirty merge.

**Describe alternatives you've considered**
I could just copy that section of your source, but that wouldn't credit you fairly or link back for possible updates.

**Comment by mumbel** [comment]
https://github.com/mumbel/ghidra_riscv

Think it works, got an .so loaded into the 9.1.x BETA (ghidra-sre.org)

**Comment by VTCAKAVSMoACE** [comment]
Superb, thank you!
