### ISSUE TITLE
size of "long" for risc64

### ISSUE THREAD

**Issue by jimparis** [mumbel/ghidra#23]
The size of "long" in [riscv64-fp.cspec](https://github.com/mumbel/ghidra_riscv/blob/59065520c381c5e8b27ce239fc3863b62e78109e/data/languages/riscv64-fp.cspec#L12) appears wrong to me; should it be 8 bytes? `sizeof(long)==8` in the Kendryte k210 toolchain.  Because of this ghidra thinks uint64_t is 4 bytes.

**Comment by mumbel** [comment]
@jimparis  Thanks, for letting me know, sorry for noticing this earlier

https://github.com/NationalSecurityAgency/ghidra/pull/2590

**Comment by mumbel** [comment]
Just got merged.  Looks like 10.2 will have the fix
