### ISSUE TITLE
mirror addresses 

### ISSUE THREAD

**Issue by esaulenka** [mumbel/ghidra#9]
Sorry for question, but i don't found, how to specify that addresses 0x80001234 and 0xA0001234 point to the same location?

**Comment by mumbel** [comment]
Not certain on best approach, but you can file->'add to program' and select same ROM.  In that popup you'll want to click 'Options' where you can specify alternate load address, offset into file, data Len, and block name

**Comment by esaulenka** [comment]
Ok, thanks. IDA converts this automatically (when i name dword 0xA000abcd as pointer, it become indicate to 0x8000abcd).
For me, this task looks like good start point to learn how to write plugins for Ghidra ;-)

**Comment by mumbel** [comment]
I asked a Dev in my pull request.  Seems possible both in code and when loading from his answer

**Comment by mumbel** [comment]
Sorry hadn't had much time to play with this.  Do not know how to automate this, but it seems really good from a quick glance with this setup:

- load rom at 0x80000000, don't auto-analyze yet
- open memory map settings, add new,  add a name, offset 0xA0000000, length 0x180000, click execute check-box, choose byte-mapped in drop down, new address option should already be 0x80000000.
- open memory map settings, add new,  add a name, offset 0xC0000000, length 0x180000, click execute check-box, choose byte-mapped in drop down, new address option should already be 0x80000000.
- save memory map
- auto-analyze
